---
driver:
  name: vagrant

  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

  customize:
    cpus: 2
    memory: 2048
  gui: false
  # synced_folders:
  #   - ["./", "/sources"]
  #   - ["~/chef-kits", "/chef-kits"]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  deprecations_as_errors: true
  # enforce_idempotency: true
  # multiple_converge: 2
  log_level: info
  require_chef_omnibus: true
  # require_chef_omnibus: 12.19.36
  # require_chef_omnibus: 13


verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  # -name: centos-6.7
  - name: centos-7.3
  # - name: win2012r2
  # - name: mwrock/Windows2012R2
  # - name: mwrock/Windows2012R2Full
  # - name: mwrock/Windows2016
  # - name: tricky/solaris11-chef
  # - name: tricky/solaris10-chef

suites:
  - name: default
    run_list:
      - recipe[spring_boot::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_client:
        config:
          log_level: info
      ohai:
        disabled_plugins: [ ]
